//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EVRAZ_Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class Products_Ved
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Products_Ved()
        {
            this.VEDOMOST = new HashSet<VEDOMOST>();
        }
    
        public int ID { get; set; }
        public string Kleim { get; set; }
        public int Charact { get; set; }
        public int Profile { get; set; }
        public int Marka { get; set; }
        public int ID_Place { get; set; }
    
        public virtual Charact_Prod Charact_Prod { get; set; }
        public virtual Defects_Prod Defects_Prod { get; set; }
        public virtual Marka_Prod Marka_Prod { get; set; }
        public virtual Place_Ved Place_Ved { get; set; }
        public virtual Profile_Prod Profile_Prod { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VEDOMOST> VEDOMOST { get; set; }
    }
}
