//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EVRAZ_Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class VEDOMOST
    {
        public int ID { get; set; }
        public int Type_ved { get; set; }
        public System.DateTime DateTime { get; set; }
        public int Products { get; set; }
        public int Person { get; set; }
        public int Place { get; set; }
    
        public virtual Personal_Ved Personal_Ved { get; set; }
        public virtual Place_Ved Place_Ved { get; set; }
        public virtual Products_Ved Products_Ved { get; set; }
        public virtual Type_Ved Type_Ved1 { get; set; }
    }
}
